//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamWork.ServiceProgramMessenge {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProgramMessenge.IServiceProgramMessenger", CallbackContract=typeof(TeamWork.ServiceProgramMessenge.IServiceProgramMessengerCallback))]
    public interface IServiceProgramMessenger {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/sendSystemMessageSPM")]
        void sendSystemMessageSPM(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/sendSystemMessageSPM")]
        System.Threading.Tasks.Task sendSystemMessageSPMAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/ConnectSPM")]
        void ConnectSPM(string user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/ConnectSPM")]
        System.Threading.Tasks.Task ConnectSPMAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/DisconnectSPM")]
        void DisconnectSPM(string user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/DisconnectSPM")]
        System.Threading.Tasks.Task DisconnectSPMAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/UpdateProjectsSPM")]
        void UpdateProjectsSPM();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/UpdateProjectsSPM")]
        System.Threading.Tasks.Task UpdateProjectsSPMAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/UpdateTasksSPM")]
        void UpdateTasksSPM();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/UpdateTasksSPM")]
        System.Threading.Tasks.Task UpdateTasksSPMAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/UpdateEmployeesSPM")]
        void UpdateEmployeesSPM();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/UpdateEmployeesSPM")]
        System.Threading.Tasks.Task UpdateEmployeesSPMAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProgramMessengerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/sendSystemMessageCB")]
        void sendSystemMessageCB(string mes);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/UpdateProjectsCB")]
        void UpdateProjectsCB();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/UpdateTasksCB")]
        void UpdateTasksCB();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceProgramMessenger/UpdateEmployeesCB")]
        void UpdateEmployeesCB();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProgramMessengerChannel : TeamWork.ServiceProgramMessenge.IServiceProgramMessenger, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProgramMessengerClient : System.ServiceModel.DuplexClientBase<TeamWork.ServiceProgramMessenge.IServiceProgramMessenger>, TeamWork.ServiceProgramMessenge.IServiceProgramMessenger {
        
        public ServiceProgramMessengerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceProgramMessengerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceProgramMessengerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProgramMessengerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProgramMessengerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void sendSystemMessageSPM(string message) {
            base.Channel.sendSystemMessageSPM(message);
        }
        
        public System.Threading.Tasks.Task sendSystemMessageSPMAsync(string message) {
            return base.Channel.sendSystemMessageSPMAsync(message);
        }
        
        public void ConnectSPM(string user) {
            base.Channel.ConnectSPM(user);
        }
        
        public System.Threading.Tasks.Task ConnectSPMAsync(string user) {
            return base.Channel.ConnectSPMAsync(user);
        }
        
        public void DisconnectSPM(string user) {
            base.Channel.DisconnectSPM(user);
        }
        
        public System.Threading.Tasks.Task DisconnectSPMAsync(string user) {
            return base.Channel.DisconnectSPMAsync(user);
        }
        
        public void UpdateProjectsSPM() {
            base.Channel.UpdateProjectsSPM();
        }
        
        public System.Threading.Tasks.Task UpdateProjectsSPMAsync() {
            return base.Channel.UpdateProjectsSPMAsync();
        }
        
        public void UpdateTasksSPM() {
            base.Channel.UpdateTasksSPM();
        }
        
        public System.Threading.Tasks.Task UpdateTasksSPMAsync() {
            return base.Channel.UpdateTasksSPMAsync();
        }
        
        public void UpdateEmployeesSPM() {
            base.Channel.UpdateEmployeesSPM();
        }
        
        public System.Threading.Tasks.Task UpdateEmployeesSPMAsync() {
            return base.Channel.UpdateEmployeesSPMAsync();
        }
    }
}
